id = "rapture-theme"
name = "Rapture"
version = "1.0.1"
schema_version = 1
authors = ["Pustur <loris.bettazza@gmail.com>" , "gabors0 <gabors0@proton.me>"]
description = "A dark blue theme with bright accents inspired by the fictional city of Rapture, ported to Zed! Original by Pustur"
repository = "https://github.com/gabors0/rapture-zed"
